#!/bin/bash
set -e
set -o pipefail

# Purpose: Verify that architecture-specific images exist in the registry before creating a manifest.

# Input environment variables (expected from workflow env block):
# - INPUT_REGISTRY_IMAGE
# - INPUT_BASE_VERSION_TAG_NO_ARCH (e.g., bookworm-slim_wine-staging-10.5_dev)
# - INPUT_BASE_CODENAME_TAG_NO_ARCH (e.g., bookworm-wine-staging_dev)
# - INPUT_BOX86_VERSION_FOR_TAG (from manifest_prepare_meta, e.g. 0.3.9-d0aad67)
# - INPUT_BOX64_VERSION_FOR_TAG (from manifest_prepare_meta, e.g. 0.3.5-3542c88)


# Helper function to construct arch-specific codename tag
# The arch-specific codename tag includes Box versions directly in its name
# if they were determined by build_prepare_docker_meta.sh for the arm64 build.
# This function reconstructs that potential arch-specific tag.
construct_arch_codename_tag() {
    local base_codename_tag="$1"
    local arch="$2"
    local arch_codename_tag="${base_codename_tag}-${arch}" # Start with base + arch

    # If it's arm64, the original arch-specific codename tag might have included Box versions.
    # The INPUT_BASE_CODENAME_TAG_NO_ARCH from manifest_prepare_meta.sh might *also* have them
    # if we decided to make the multi-arch codename tag Box-version-aware.
    # Let's assume the arch-specific tag was: <base_codename_tag_from_manifest_prep_without_box>_BOX86..._BOX64...-arm64
    # The INPUT_BASE_CODENAME_TAG_NO_ARCH is already the one we want to append -<arch> to.
    # So, simply appending arch should be correct if manifest_prepare_meta.sh correctly formed
    # INPUT_BASE_CODENAME_TAG_NO_ARCH to include box versions where appropriate for the *manifest name*.
    # The individual build jobs create e.g. bookworm-dev_BOX86-ver_BOX64-ver-arm64
    # And manifest_prepare_meta created MANIFEST_BASE_CODENAME_TAG to be e.g. bookworm-dev_BOX86-ver_BOX64-ver
    # So we just need to add the -<arch> suffix.

    # Correction: The arch-specific codename tags generated by build_prepare_docker_meta.sh
    # are ${tag_codename_base}-${ARCHITECTURE_VAL}.
    # And tag_codename_base includes Box versions.
    # MANIFEST_BASE_CODENAME_TAG from manifest_prepare_meta also includes these.
    # So, the logic should be:
    # For VERSIONED tags: INPUT_BASE_VERSION_TAG_NO_ARCH + "-amd64" and + "-arm64"
    # For CODENAME tags: INPUT_BASE_CODENAME_TAG_NO_ARCH + "-amd64" and + "-arm64"

    # This means the input INPUT_BASE_CODENAME_TAG_NO_ARCH must be the version that *includes*
    # the Box versions if the arm64 arch-specific image was tagged that way.
    # build_prepare_docker_meta.sh produces:
    #   TAG_CODENAME=$DEBIAN_CODENAME_VAL -> bookworm
    #   TAG_CODENAME=$TAG_CODENAME-wine-branch (if wine) -> bookworm-wine-staging
    #   TAG_CODENAME=$TAG_CODENAME_dev (if dev) -> bookworm-wine-staging_dev
    #   TAG_CODENAME=$TAG_CODENAME_BOX86-ver_BOX64-ver (if arm64 & box) -> bookworm-wine-staging_dev_BOX86-0.3.9_BOX64-0.3.5
    #   FINAL_TAG_CODENAME_ARCH = $TAG_CODENAME-arm64 -> bookworm-wine-staging_dev_BOX86-0.3.9_BOX64-0.3.5-arm64
    #
    # manifest_prepare_meta.sh produces:
    #   MANIFEST_BASE_CODENAME_TAG = bookworm-wine-staging_dev_BOX86-0.3.9_BOX64-0.3.5 (if all conditions met)
    #
    # So to verify, we need:
    #   ${MANIFEST_BASE_CODENAME_TAG}-amd64 (but without box for amd64)
    #   ${MANIFEST_BASE_CODENAME_TAG}-arm64 (this one is fine as MANIFEST_BASE_CODENAME_TAG includes box)
    # This is getting complicated. The simplest is that the arch-specific tags are known.
    # The manifest_verify_images script should check for the *exact* tags that were pushed by the build job.

    # Let's simplify: the manifest creation job will *use* INPUT_BASE_VERSION_TAG_NO_ARCH and INPUT_BASE_CODENAME_TAG_NO_ARCH
    # to *find* the amd64 and arm64 suffixed versions.
    # So, this script needs to check for:
    # ${INPUT_BASE_VERSION_TAG_NO_ARCH}-amd64, ${INPUT_BASE_VERSION_TAG_NO_ARCH}-arm64
    # ${INPUT_BASE_CODENAME_TAG_NO_ARCH}-amd64, ${INPUT_BASE_CODENAME_TAG_NO_ARCH}-arm64
    # This assumes that the CODENAME tag for amd64 *does not* contain _BOX... parts,
    # and the CODENAME tag for arm64 *does* if applicable.
    # The MANIFEST_BASE_CODENAME_TAG from manifest_prepare_meta.sh includes Box versions.
    # This means `${INPUT_BASE_CODENAME_TAG_NO_ARCH}-amd64` would wrongly include Box versions.

    # Correct approach:
    # The build job creates:
    # - For versioned tags: <base_image_tag>_<compat_details>_<dev_suffix>-<arch>
    # - For codename tags: <codename>_<compat_details_no_ver>_<dev_suffix>[_BOX_details]-<arch>
    # The manifest_prepare_meta.sh creates:
    # - MANIFEST_BASE_VERSION_TAG = <base_image_tag>_<compat_details>_<dev_suffix>
    # - MANIFEST_BASE_CODENAME_TAG = <codename>_<compat_details_no_ver>_<dev_suffix>[_BOX_details]
    # So, we verify:
    # - ${MANIFEST_BASE_VERSION_TAG}-amd64 AND ${MANIFEST_BASE_VERSION_TAG}-arm64
    # - The codename tag for amd64 will be MANIFEST_BASE_CODENAME_TAG but *without* any _BOX... parts, then -amd64.
    # - The codename tag for arm64 will be MANIFEST_BASE_CODENAME_TAG (which includes _BOX...), then -arm64.

    local base_tag_for_arch="$1" # This is the base *without* box for amd64, *with* box for arm64
    local final_tag_to_check="${base_tag_for_arch}-${arch}"

    echo "Verifying: ${INPUT_REGISTRY_IMAGE}:${final_tag_to_check}"
    if ! docker buildx imagetools inspect "${INPUT_REGISTRY_IMAGE}:${final_tag_to_check}" >/dev/null 2>&1; then
      echo "::error::Architecture-specific image ${INPUT_REGISTRY_IMAGE}:${final_tag_to_check} not found in registry."
      exit 1
    fi
    echo "Verified: ${INPUT_REGISTRY_IMAGE}:${final_tag_to_check}"
}


main() {
  echo "Verifying existence of architecture-specific images for manifest creation..."

  # Verify VERSIONED tags
  construct_arch_codename_tag "${INPUT_BASE_VERSION_TAG_NO_ARCH}" "amd64"
  construct_arch_codename_tag "${INPUT_BASE_VERSION_TAG_NO_ARCH}" "arm64"

  # Verify CODENAME tags
  # For amd64, codename tag should NOT have Box versions.
  # Strip _BOX... if present from INPUT_BASE_CODENAME_TAG_NO_ARCH for amd64 check.
  local codename_base_amd64
  codename_base_amd64=$(echo "${INPUT_BASE_CODENAME_TAG_NO_ARCH}" | sed -E 's/_BOX86-[^_]+_BOX64-[^_]+//')
  construct_arch_codename_tag "${codename_base_amd64}" "amd64"

  # For arm64, codename tag SHOULD have Box versions if they were part of INPUT_BASE_CODENAME_TAG_NO_ARCH
  construct_arch_codename_tag "${INPUT_BASE_CODENAME_TAG_NO_ARCH}" "arm64" # This base already has Box details if applicable

  echo "All required architecture-specific images verified to exist."
}

main
